/**
 * Writing source documents.
 *
 * Four facts are decided here and never accepted from a request:
 *   project_id       — from the route, re-read through the caller's own client
 *   created_by       — the session user
 *   revision_number  — 1, or the predecessor's number plus one, read from the database
 *   document_key     — inherited from the predecessor, generated by the database otherwise
 *
 * Everything runs on a **user-scoped** client. There is no service-role client in this
 * file and there must not be: RLS is the security boundary for the whole request path.
 *
 * Three rules are enforced in the database as well as here — archived projects,
 * locked revisions, and revision-chain integrity (20260724000008). That is not
 * belt-and-braces for its own sake: this layer produces a sentence a person can act
 * on, and the database produces the guarantee.
 */

import type { SupabaseClient } from "@supabase/supabase-js";
import {
  sourceContentSchema,
  toMetadata,
  type SourceContentInput,
} from "../contracts/source";
import { assertProjectIsActive, GATE_MESSAGES } from "../projects/guards";

export type ServiceResult<T> =
  | { ok: true; data: T }
  | { ok: false; error: string; fieldErrors?: Record<string, string> };

/** Postgres errors are for the log. The user gets a sentence, never a policy name. */
function failure(context: string, detail: string, message: string): ServiceResult<never> {
  console.error(`[sources] ${context}: ${detail}`);
  return { ok: false, error: message };
}

/**
 * A refusal that came from a trigger, translated. The message text is matched rather
 * than the SQLSTATE because every guard raises `restrict_violation` — the code says
 * "a rule stopped you", the text says which rule.
 */
function translate(detail: string): string | null {
  if (/locked/i.test(detail)) {
    return "This revision has already been analysed and can no longer be edited. Create a new revision instead.";
  }
  if (/archived/i.test(detail)) return GATE_MESSAGES.archived;
  if (/revision/i.test(detail)) {
    return "This source has changed since the page was opened. Reload and try again.";
  }
  return null;
}

async function currentUserId(client: SupabaseClient): Promise<string | null> {
  const {
    data: { user },
  } = await client.auth.getUser();
  return user?.id ?? null;
}

export async function createSource(
  client: SupabaseClient,
  projectId: string,
  rawInput: SourceContentInput,
): Promise<ServiceResult<{ sourceId: string }>> {
  // Re-parsed even though the action parsed it: this function is a boundary in its
  // own right and a future caller may not be the form.
  const parsed = sourceContentSchema.safeParse(rawInput);
  if (!parsed.success) return { ok: false, error: "Some fields need attention." };
  const input = parsed.data;

  const gate = await assertProjectIsActive(client, projectId);
  if (!gate.ok) return { ok: false, error: GATE_MESSAGES[gate.reason] };

  const userId = await currentUserId(client);
  if (!userId) return { ok: false, error: "Your session has expired. Sign in again." };

  const { data, error } = await client
    .from("source_documents")
    .insert({
      project_id: gate.projectId,
      title: input.title,
      kind: input.kind,
      // Verbatim. Not trimmed, not normalised, not re-encoded.
      raw_text: input.rawText,
      metadata: toMetadata(input),
      created_by: userId,
      // revision_number and document_key are omitted on purpose: the column defaults
      // (1, and a fresh uuid) are the only things allowed to set them.
    })
    .select("id")
    .single();

  if (error) {
    return failure(
      "create",
      error.message,
      translate(error.message) ?? "The source could not be saved. Try again.",
    );
  }
  return { ok: true, data: { sourceId: data.id } };
}

/**
 * Editing an unlocked revision in place.
 *
 * The lock is not re-read here and then acted on — that check-then-write gap is
 * exactly where a concurrent analysis run would slip through. The UPDATE is issued
 * and the trigger decides; if the revision was locked a millisecond ago, the write
 * fails and nothing is overwritten.
 */
export async function updateSource(
  client: SupabaseClient,
  projectId: string,
  sourceId: string,
  rawInput: SourceContentInput,
): Promise<ServiceResult<{ sourceId: string }>> {
  const parsed = sourceContentSchema.safeParse(rawInput);
  if (!parsed.success) return { ok: false, error: "Some fields need attention." };
  const input = parsed.data;

  const gate = await assertProjectIsActive(client, projectId);
  if (!gate.ok) return { ok: false, error: GATE_MESSAGES[gate.reason] };

  const { data, error } = await client
    .from("source_documents")
    .update({
      title: input.title,
      kind: input.kind,
      raw_text: input.rawText,
      metadata: toMetadata(input),
    })
    .eq("project_id", gate.projectId)
    .eq("id", sourceId)
    .select("id");

  if (error) {
    return failure(
      "update",
      error.message,
      translate(error.message) ?? "The source could not be saved. Try again.",
    );
  }
  // RLS refuses by matching nothing rather than raising, so zero rows is a refusal,
  // not an empty success.
  if ((data ?? []).length === 0) {
    return { ok: false, error: "This source is no longer editable." };
  }
  return { ok: true, data: { sourceId } };
}

/**
 * Superseding a locked revision.
 *
 * Every field of the new row's identity is read from the predecessor **in the
 * database**, addressed by the route's project id and source id. Nothing about the
 * chain travels through the browser, so there is no hidden input to tamper with; the
 * insert trigger then re-derives the same facts and rejects the row if they disagree.
 */
export async function createSourceRevision(
  client: SupabaseClient,
  projectId: string,
  previousId: string,
  rawInput: SourceContentInput,
): Promise<ServiceResult<{ sourceId: string }>> {
  const parsed = sourceContentSchema.safeParse(rawInput);
  if (!parsed.success) return { ok: false, error: "Some fields need attention." };
  const input = parsed.data;

  const gate = await assertProjectIsActive(client, projectId);
  if (!gate.ok) return { ok: false, error: GATE_MESSAGES[gate.reason] };

  const userId = await currentUserId(client);
  if (!userId) return { ok: false, error: "Your session has expired. Sign in again." };

  const { data: previous, error: previousError } = await client
    .from("source_documents")
    .select("id, document_key, revision_number")
    .eq("project_id", gate.projectId)
    .eq("id", previousId)
    .maybeSingle();

  if (previousError) {
    return failure("revision lookup", previousError.message, "The source could not be read.");
  }
  if (!previous) return { ok: false, error: "This source is not available." };

  const { data, error } = await client
    .from("source_documents")
    .insert({
      project_id: gate.projectId,
      title: input.title,
      kind: input.kind,
      raw_text: input.rawText,
      metadata: toMetadata(input),
      created_by: userId,
      document_key: previous.document_key,
      revision_number: previous.revision_number + 1,
      supersedes_source_document_id: previous.id,
    })
    .select("id")
    .single();

  if (error) {
    // The unique (document_key, revision_number) index is what a lost race looks like.
    const conflict = /duplicate key|unique/i.test(error.message)
      ? "Someone has already created the next revision of this source. Reload to see it."
      : null;
    return failure(
      "revision",
      error.message,
      conflict ?? translate(error.message) ?? "The revision could not be created. Try again.",
    );
  }
  return { ok: true, data: { sourceId: data.id } };
}
